export type CompositionMode = 'MANUAL' | 'AI_COMPOSER';

export type ToneType = 
  | 'Professional'
  | 'Friendly'
  | 'Formal'
  | 'Casual'
  | 'Polite'
  | 'Persuasive'
  | 'Apologetic';

export type EngineState =
  | 'IDLE'
  | 'SELECT_COMPOSITION_MODE'
  // Manual Flow
  | 'MANUAL_WAITING_RECIPIENT'
  | 'CONFIRM_RECIPIENT'
  | 'MANUAL_WAITING_SUBJECT'
  | 'MANUAL_WAITING_BODY'
  // AI Flow
  | 'AI_WAITING_TOPIC'
  | 'AI_WAITING_TONE'
  | 'AI_WAITING_SPECIFICS'
  | 'AI_GENERATING'
  // Common Flow
  | 'EMAIL_PREVIEW'
  | 'SUGGESTION_MODE'
  | 'CONFIRM_SEND'
  | 'SENDING'
  | 'COMPLETE';

export interface EmailDraft {
  recipient: string;
  subject: string;
  body: string;
  topic?: string;
  tone?: ToneType;
  specifics?: string;
  isSubjectAutoGenerated?: boolean;
}

export interface ChatMessage {
  id: string;
  sender: 'user' | 'assistant';
  text: string;
  timestamp: Date;
  state: EngineState;
}

export interface StateMachineContext {
  currentState: EngineState;
  mode: CompositionMode | null;
  draft: EmailDraft;
  messages: ChatMessage[];
  isListening: boolean;
  isSpeaking: boolean;
  errorMessage: string | null;
}
