import { useState, useCallback } from 'react';
import type { StateMachineContext, EngineState, ToneType, ChatMessage } from './types';
import { INITIAL_CONTEXT, isValidEmail, parseSpokenEmail, generateAssistantPrompt } from './conversationMachine';

export function useConversation() {
  const [context, setContext] = useState<StateMachineContext>(INITIAL_CONTEXT);

  const addMessage = useCallback((sender: 'user' | 'assistant', text: string, state: EngineState) => {
    const newMessage: ChatMessage = {
      id: Math.random().toString(36).substring(2, 9),
      sender,
      text,
      timestamp: new Date(),
      state,
    };
    setContext((prev) => ({
      ...prev,
      messages: [...prev.messages, newMessage],
    }));
  }, []);

  const transitionTo = useCallback((nextState: EngineState, updatedDraftPartial?: Partial<StateMachineContext['draft']>) => {
    setContext((prev) => {
      const newDraft = updatedDraftPartial ? { ...prev.draft, ...updatedDraftPartial } : prev.draft;
      const prompt = generateAssistantPrompt(nextState, prev.mode, newDraft);

      const assistantMsg: ChatMessage = {
        id: Math.random().toString(36).substring(2, 9),
        sender: 'assistant',
        text: prompt,
        timestamp: new Date(),
        state: nextState,
      };

      return {
        ...prev,
        currentState: nextState,
        draft: newDraft,
        errorMessage: null,
        messages: [...prev.messages, assistantMsg],
      };
    });
  }, []);

  const startConversation = useCallback(() => {
    setContext((prev) => ({
      ...prev,
      currentState: 'SELECT_COMPOSITION_MODE',
      errorMessage: null,
    }));
    addMessage('assistant', generateAssistantPrompt('SELECT_COMPOSITION_MODE', null, INITIAL_CONTEXT.draft), 'SELECT_COMPOSITION_MODE');
  }, [addMessage]);

  const selectMode = useCallback((mode: 'MANUAL' | 'AI_COMPOSER') => {
    const nextState = mode === 'MANUAL' ? 'MANUAL_WAITING_RECIPIENT' : 'AI_WAITING_TOPIC';
    setContext((prev) => ({
      ...prev,
      mode,
    }));
    addMessage('user', mode === 'MANUAL' ? 'Manual Composition' : 'AI Composer', 'SELECT_COMPOSITION_MODE');
    transitionTo(nextState);
  }, [addMessage, transitionTo]);

  const handleUserInput = useCallback((input: string) => {
    const text = input.trim();
    if (!text) return;

    addMessage('user', text, context.currentState);

    switch (context.currentState) {
      case 'IDLE': {
        const lower = text.toLowerCase();
        if (lower.includes('send') || lower.includes('email') || lower.includes('write') || lower.includes('compose')) {
          startConversation();
        } else {
          addMessage('assistant', 'Say "Send an email" or tap the compose button to start.', 'IDLE');
        }
        break;
      }

      case 'SELECT_COMPOSITION_MODE': {
        const lower = text.toLowerCase();
        if (lower.includes('manual') || lower.includes('myself') || lower.includes('dictate')) {
          selectMode('MANUAL');
        } else if (lower.includes('ai') || lower.includes('compose') || lower.includes('help')) {
          selectMode('AI_COMPOSER');
        } else {
          addMessage('assistant', "I didn't quite catch that. Would you like to dictate the email yourself or have me compose it?", 'SELECT_COMPOSITION_MODE');
        }
        break;
      }

      case 'MANUAL_WAITING_RECIPIENT': {
        const parsedEmail = parseSpokenEmail(text);
        if (isValidEmail(parsedEmail)) {
          transitionTo('MANUAL_WAITING_SUBJECT', { recipient: parsedEmail });
        } else {
          addMessage('assistant', "That doesn't appear to be a valid email address. Could you repeat it?", 'MANUAL_WAITING_RECIPIENT');
        }
        break;
      }

      case 'MANUAL_WAITING_SUBJECT': {
        const lower = text.toLowerCase();
        if (lower.includes('generate one') || lower.includes('auto') || lower.includes('ai')) {
          transitionTo('MANUAL_WAITING_BODY', { subject: 'Automated Subject', isSubjectAutoGenerated: true });
        } else {
          transitionTo('MANUAL_WAITING_BODY', { subject: text });
        }
        break;
      }

      case 'MANUAL_WAITING_BODY': {
        setContext((prev) => ({ ...prev, draft: { ...prev.draft, body: text } }));
        transitionTo('EMAIL_PREVIEW', { body: text });
        break;
      }

      case 'AI_WAITING_TOPIC': {
        transitionTo('AI_WAITING_TONE', { topic: text });
        break;
      }

      case 'AI_WAITING_TONE': {
        const toneStr = text.charAt(0).toUpperCase() + text.slice(1).toLowerCase();
        const validTones: ToneType[] = ['Professional', 'Friendly', 'Formal', 'Casual', 'Polite', 'Persuasive', 'Apologetic'];
        const selectedTone = validTones.find(t => t.toLowerCase() === toneStr.toLowerCase()) || 'Professional';
        
        transitionTo('AI_WAITING_SPECIFICS', { tone: selectedTone });
        break;
      }

      case 'AI_WAITING_SPECIFICS': {
        // Simulate AI generation placeholder
        const topic = context.draft.topic || 'Important Update';
        const generatedSubject = `Regarding: ${topic}`;
        const generatedBody = `Dear Recipient,\n\nI am writing to discuss ${topic}. ${text ? 'Additional context: ' + text + '.' : ''}\n\nPlease let me know your thoughts.\n\nBest regards,\n[Your Name]`;
        
        setContext((prev) => ({
          ...prev,
          currentState: 'AI_GENERATING',
        }));
        
        setTimeout(() => {
          if (!context.draft.recipient) {
            // Ask for recipient if AI flow started before recipient
            transitionTo('MANUAL_WAITING_RECIPIENT', {
              subject: generatedSubject,
              body: generatedBody,
              specifics: text
            });
          } else {
            transitionTo('EMAIL_PREVIEW', {
              subject: generatedSubject,
              body: generatedBody,
              specifics: text
            });
          }
        }, 1000);
        break;
      }

      case 'EMAIL_PREVIEW':
      case 'SUGGESTION_MODE': {
        const lower = text.toLowerCase();
        if (lower.includes('send')) {
          transitionTo('CONFIRM_SEND');
        } else if (lower.includes('edit') || lower.includes('change') || lower.includes('rewrite') || lower.includes('shorten') || lower.includes('improve')) {
          addMessage('assistant', `I can help update your draft. Try clicking a suggestion chip or tell me what to modify.`, 'SUGGESTION_MODE');
        } else {
          addMessage('assistant', `Draft updated with: "${text}". Would you like to edit it further or send it?`, 'EMAIL_PREVIEW');
          setContext((prev) => ({
            ...prev,
            draft: { ...prev.draft, body: prev.draft.body + `\n${text}` }
          }));
        }
        break;
      }

      case 'CONFIRM_SEND': {
        const lower = text.toLowerCase();
        if (lower.includes('yes') || lower.includes('send') || lower.includes('sure') || lower.includes('ok') || lower.includes('confirm')) {
          setContext((prev) => ({ ...prev, currentState: 'SENDING' }));
          addMessage('assistant', 'Sending your email via Gmail...', 'SENDING');
          setTimeout(() => {
            transitionTo('COMPLETE');
          }, 1500);
        } else {
          addMessage('assistant', 'Sending cancelled. What would you like to edit?', 'EMAIL_PREVIEW');
          setContext((prev) => ({ ...prev, currentState: 'EMAIL_PREVIEW' }));
        }
        break;
      }

      case 'COMPLETE': {
        startConversation();
        break;
      }
    }
  }, [addMessage, context.currentState, context.draft, selectMode, startConversation, transitionTo]);

  const applyToneSuggestion = useCallback((tone: ToneType) => {
    setContext((prev) => {
      const updatedBody = `[Tone adjusted to ${tone}]\n\n` + prev.draft.body;
      return {
        ...prev,
        draft: { ...prev.draft, tone, body: updatedBody }
      };
    });
    addMessage('user', `Apply tone: ${tone}`, context.currentState);
    addMessage('assistant', `Adjusted email tone to ${tone}.`, 'EMAIL_PREVIEW');
  }, [addMessage, context.currentState]);

  const updateDraftDirectly = useCallback((field: keyof StateMachineContext['draft'], value: string) => {
    setContext((prev) => ({
      ...prev,
      draft: { ...prev.draft, [field]: value }
    }));
  }, []);

  const resetEngine = useCallback(() => {
    setContext(INITIAL_CONTEXT);
  }, []);

  return {
    context,
    startConversation,
    selectMode,
    handleUserInput,
    applyToneSuggestion,
    updateDraftDirectly,
    transitionTo,
    resetEngine,
  };
}
